" __     _____ __  __ ____   ____ 
" \ \   / /_ _|  \/  |  _ \ / ___|
"  \ \ / / | || |\/| | |_) | |    
"  _\ V /  | || |  | |  _ <| |___ 
" (_)\_/  |___|_|  |_|_| \_\\____|
" 

source $HOME/.vim/vimrc.d/augroups.vimrc
source $HOME/.vim/vimrc.d/plugins.vimrc
source $HOME/.vim/vimrc.d/keymaps.vimrc
source $HOME/.vim/vimrc.d/general.vimrc
