execute pathogen#infect()

" Auto-reload vimrc
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

" Enable syntax specific behaviors 
filetype on
filetype indent on
syntax on

set showmatch

set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase
set smartcase		" overrides ignore-case search if searching for Upper case letters

setlocal spell spelllang=en_us " Enable spell checks
set number " Enable line numbers 
set cursorline " highlight current line
set backspace=indent,eol,start " Make backspace work naturally (delete indentation and new lines)
