### Include dotfiles ###
source ~/.dotfiles/zsh/oh-my-zsh.sh
source ~/.dotfiles/zsh/functions.sh
source ~/.dotfiles/zsh/aliases.sh
source ~/.dotfiles/zsh/runtimes.sh
source ~/.dotfiles/zsh/tools.sh
### -------------------------- ###

export EDITOR='vim'